#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/ganwei-remotedesk/ganwei-remotedesk /usr/bin/ganwei-remotedesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/ganwei-remotedesk.service ]; then
			rm /etc/systemd/system/ganwei-remotedesk.service /usr/lib/systemd/system/ganwei-remotedesk.service /usr/lib/systemd/user/ganwei-remotedesk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/ganwei-remotedesk/files/systemd/ganwei-remotedesk.service /usr/lib/systemd/system/ganwei-remotedesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload rustdesk.service: Unit rustdesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/rustdesk.service:10: Executable path is not absolute: pkill -f "rustdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/ganwei-remotedesk.service
		fi
		systemctl daemon-reload
		systemctl enable ganwei-remotedesk
		systemctl start ganwei-remotedesk
	fi
fi
