name: Self-hosted desktop clients

on:
  workflow_dispatch:
  push:
    branches:
      - feat/self-hosted-account-address-book
    paths:
      - ".github/workflows/self-hosted-desktop-build.yml"
      - ".github/workflows/flutter-build.yml"

jobs:
  build-desktop-clients:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "self-hosted"
      publish-release: false
      desktop-only: true
